// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CreateEvent(arg1:backend.Event):Promise<void>;

export function GetEvents():Promise<Array<backend.Event>>;
